{% set name = "pylance" %}
{% set version = "11.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lancedb/lance/archive/refs/tags/v{{ version }}.tar.gz
  sha256: e2704758360cb3e38b038dd7cbcdea74970c208e5fbe57c1cc3ecbedb72f823c

build:
  number: 0
  skip: true  # [py<39]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - maturin <2                             # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    - libprotobuf
  host:
    - python
    - pip
    - maturin <2
    - openssl
  run:
    - python
    - numpy >=1.22
    - pyarrow >=14
    - lance-namespace >=0.8.5,<0.9

test:
  imports:
    - lance
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/lancedb/lance
  summary: python wrapper for Lance columnar format
  license: Apache-2.0
  license_file:
    - LICENSE
    - python/LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - yhori991
